name: Github Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --ignore-scripts --frozen-lockfile
      - name: Code quality checks
        run: yarn prettier:check && yarn lint && yarn typescript:check
